import java.io.IOException
import java.net.URI

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
}

allprojects {
    repositories {
        mavenCentral()
        maven("https://gitlab.com/api/v4/projects/10077943/packages/maven")
        maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://repo.codemc.io/repository/maven-public/")
    }
}

// ---- Pinned Paper server: ./gradlew run ----------------------------------
val paperVersion = libs.versions.paperVersion.get()
val paperBuild = libs.versions.paperBuild.get()
val paperJarName = "paper-$paperVersion-$paperBuild.jar"

val paperUrl =
    "https://api.papermc.io/v2/projects/paper/versions/$paperVersion/builds/$paperBuild/downloads/$paperJarName"

val pluginApiVersion = libs.versions.pluginApi.get()
val pluginApiRuntimeJarName = "runtime-$pluginApiVersion.jar"

val pluginApiRuntimeUrl =
    "https://gitlab.com/api/v4/projects/10077943/packages/maven/io/github/commandertvis/plugin/runtime/" +
        "$pluginApiVersion/$pluginApiRuntimeJarName"

val holoVersion = libs.versions.holographicdisplays.get()
val holoJarName = "HolographicDisplays-$holoVersion.jar"
val holoUrl =
    "https://repo.codemc.io/repository/maven-public/me/filoghost/holographicdisplays/" +
        "holographicdisplays-plugin/$holoVersion/holographicdisplays-plugin-$holoVersion.jar"

val runDir = layout.projectDirectory.dir("run")
val paperJar = runDir.file(paperJarName).asFile
val pluginApiRuntimeJar = runDir.dir("plugins").file(pluginApiRuntimeJarName).asFile
val holoJar = runDir.dir("plugins").file(holoJarName).asFile

val downloadPaper by tasks.registering {
    group = "server"
    description = "Downloads pinned Paper $paperVersion build $paperBuild to ./run"
    outputs.file(paperJar)
    doLast {
        paperJar.parentFile.mkdirs()
        if (!paperJar.exists()) {
            logger.lifecycle("Fetching $paperJarName...")
            URI(paperUrl).toURL().openStream().use { input ->
                paperJar.outputStream().use { input.copyTo(it) }
            }
        }
    }
}

val downloadPluginApiRuntime by tasks.registering {
    group = "server"
    description = "Downloads plugin-api runtime $pluginApiVersion from GitLab next to our plugin"
    outputs.file(pluginApiRuntimeJar)
    doLast {
        pluginApiRuntimeJar.parentFile.mkdirs()
        if (pluginApiRuntimeJar.exists()) return@doLast
        logger.lifecycle("Fetching $pluginApiRuntimeJarName from GitLab...")
        URI(pluginApiRuntimeUrl).toURL().openStream().use { input ->
            pluginApiRuntimeJar.outputStream().use { input.copyTo(it) }
        }
    }
}

val downloadHolographicDisplays by tasks.registering {
    group = "server"
    description = "Downloads pinned HolographicDisplays $holoVersion to ./run/plugins"
    outputs.file(holoJar)
    doLast {
        holoJar.parentFile.mkdirs()
        if (holoJar.exists()) return@doLast
        logger.lifecycle("Fetching $holoJarName...")
        URI(holoUrl).toURL().openStream().use { input ->
            holoJar.outputStream().use { input.copyTo(it) }
        }
    }
}

val acceptEula by tasks.registering {
    group = "server"
    description = "Writes eula=true to ./run/eula.txt"
    val eula = runDir.file("eula.txt").asFile
    outputs.file(eula)
    doLast {
        eula.parentFile.mkdirs()
        eula.writeText("eula=true\n")
    }
}

val DEV_RCON_PASSWORD = "pumpkin-dev"
val DEV_RCON_PORT = 25575

val wipeWorld by tasks.registering {
    group = "server"
    description = "Removes any persisted Bukkit worlds so each runServer starts with a fresh flat world"
    delete(
        runDir.dir("world"),
        runDir.dir("world_nether"),
        runDir.dir("world_the_end"),
    )
}

val configureServer by tasks.registering {
    group = "server"
    description = "Writes a complete server.properties tuned for local AI demos"
    val props = runDir.file("server.properties").asFile
    outputs.file(props)

    doLast {
        props.parentFile.mkdirs()
        props.writeText(
            """
            # Auto-generated by ./gradlew configureServer - edits will be overwritten.
            online-mode=false
            server-port=25565
            enable-rcon=true
            rcon.port=$DEV_RCON_PORT
            rcon.password=$DEV_RCON_PASSWORD
            broadcast-rcon-to-ops=true
            enable-query=false
            level-type=FLAT
            generate-structures=false
            spawn-protection=0
            max-players=8
            view-distance=6
            difficulty=peaceful
            gamemode=creative
            allow-nether=false
            spawn-monsters=false
            spawn-animals=false
            spawn-npcs=false
            allow-flight=true
            white-list=false
            motd=PumpkinAgents dev - flat world
            """.trimIndent().trimStart() + "\n"
        )
        logger.lifecycle("server.properties written - RCON localhost:$DEV_RCON_PORT password='$DEV_RCON_PASSWORD'")
    }
}

val installPlugin by tasks.registering(Copy::class) {
    group = "server"
    description = "Copies the shadow jar into run/plugins"
    dependsOn(":plugin:shadowJar")
    from(project(":plugin").tasks.named("shadowJar"))
    into(runDir.dir("plugins"))
    doFirst {
        runDir.dir("plugins").asFile.listFiles { f -> f.name.startsWith("pumpkin-agents") }
            ?.forEach { it.delete() }
    }
}

val installMaps by tasks.registering(Copy::class) {
    group = "server"
    description = "Copies bundled benchmark maps into plugins/PumpkinAgents/maps"
    from(layout.projectDirectory.dir("maps"))
    into(runDir.dir("plugins/PumpkinAgents/maps"))
}

tasks.register<JavaExec>("runServer") {
    group = "server"
    description = "Provisions Paper + plugin-api runtime, installs the plugin, and runs the server"
    dependsOn(
        downloadPaper,
        downloadPluginApiRuntime,
        downloadHolographicDisplays,
        acceptEula,
        configureServer,
        wipeWorld,
        installPlugin,
        installMaps,
    )
    workingDir = runDir.asFile
    classpath = files(paperJar)
    mainClass = "io.papermc.paperclip.Main"
    standardInput = System.`in`
    jvmArgs = listOf("-Xms1G", "-Xmx2G", "-DPaper.IgnoreJavaVersion=true")
    args("--nogui")
    doFirst {
        if (!paperJar.exists())
            throw IOException("Paper JAR not present at $paperJar, `downloadPaper` did not run")
    }
}

tasks.register("run") {
    group = "server"
    description = "Alias of runServer"
    dependsOn("runServer")
}
